/** Normalize referrer domains for display (e.g. Www.youtube.com → youtube.com). */
export function cleanReferrerDomain(domain: string): string {
  return domain
    .replace(/^\$/, "")
    .replace(/^www\./i, "")
    .toLowerCase();
}

/** Auto-synced learning blobs that should not appear as team notes or in the archive. */
export function isAutoGeneratedLearning(text: string): boolean {
  const lower = text.toLowerCase();
  return (
    lower.includes("drove the most site traffic") ||
    lower.includes("vs last week") ||
    lower.includes("vs last period") ||
    lower.includes("new pro sub") ||
    lower.includes("visitor→") ||
    lower.includes("tooltrace ·") ||
    lower.includes("zero pro conversions") ||
    (lower.includes("visitors") && lower.includes("conversion")) ||
    (lower.includes("drove") && lower.includes("views"))
  );
}

export function formatLearningForDisplay(text: string): string {
  if (!text.trim()) return text;

  let result = text.replace(
    /(referrer[^:]*:\s*)([^\s,.\n]+)/gi,
    (_, prefix: string, domain: string) => `${prefix}${cleanReferrerDomain(domain)}`,
  );

  result = result.replace(/\bwww\./gi, "");
  return result;
}
